CREATE TABLE IF NOT EXISTS logs(
	id CHAR(36) CHARACTER SET utf8 COLLATE utf8_swedish_ci NOT NULL,
	event VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_swedish_ci NOT NULL,
	created DATETIME NOT NULL,
	PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_swedish_ci;
